LittlerootTown_newHouse_FatMan_MapScripts::
	.byte 0

LittlerootTown_newHouse_FatMan_OldWoman::
	msgbox LittlerootTown_newHouse_FatMan_Text_OldWoman, MSGBOX_NPC
	end

LittlerootTown_newHouse_FatMan_Text_OldWoman:
	.string "Have you met my son?\n"
	.string "He's the best and takes\p"
	.string "very good care of me.\p"
	.string "You should go and meet him, you\n"
	.string "would like him very much, I'm sure.$"

